/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'razing' at '5/16/16 3:59 PM' with Gradle 2.13
 *
 * @author razing, @date 5/16/16 3:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
